/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uber;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xenos
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Connection conn=null;
    Statement s=null;
    public Admin() {
        initComponents();
        //This code sets the jtable to have sorting properties by clicking on column headers
        jTable1.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CustomerManagement = new javax.swing.JButton();
        DriverManagement = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TotalFair = new javax.swing.JButton();
        TotalFairBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerManagement.setBackground(new java.awt.Color(204, 0, 0));
        CustomerManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CustomerManagement.setForeground(new java.awt.Color(46, 0, 0));
        CustomerManagement.setText("Customer Management");
        CustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerManagementActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 220, 40));

        DriverManagement.setBackground(new java.awt.Color(204, 0, 0));
        DriverManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DriverManagement.setForeground(new java.awt.Color(46, 0, 0));
        DriverManagement.setText("Driver Management");
        DriverManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverManagementActionPerformed(evt);
            }
        });
        jPanel1.add(DriverManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 40));

        Refresh.setBackground(new java.awt.Color(204, 0, 0));
        Refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Refresh.setForeground(new java.awt.Color(46, 0, 0));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ride no", "Area", "Driver id", "Driver name", "Driver contact no", "Customer id", "Customer name", "Customer contact no", "Date", "Fair "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1020, 240));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin panel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 330, 50));

        TotalFair.setBackground(new java.awt.Color(204, 0, 0));
        TotalFair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TotalFair.setForeground(new java.awt.Color(46, 0, 0));
        TotalFair.setText("Total fair");
        TotalFair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalFairActionPerformed(evt);
            }
        });
        jPanel1.add(TotalFair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 40));

        TotalFairBox.setEditable(false);
        TotalFairBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TotalFairBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalFairBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TotalFairBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uber/Black-red-space-wallpaper-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1041, 501));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalFairBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalFairBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalFairBoxActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        //Clears the table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //Fills with new data from ride database table
        try {
            
            conn = connectdb();
            String query = "select * from ride";
            s = conn.createStatement();
            ResultSet r=s.executeQuery(query);
            while(r.next()){
                int rideno=r.getInt(1),driverid=r.getInt(2),customerid=r.getInt(3);
                double fair=r.getDouble(9);
                String customername=r.getString(4),customercontact=r.getString(5),drivername=r.getString(6),drivercontact=r.getString(7),area=r.getString(8),date=r.getString(10);
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(new Object[]{rideno,area,driverid,drivername,drivercontact,customerid,customername,customercontact,date,fair});
                
            }
            conn.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void TotalFairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalFairActionPerformed
        // TODO add your handling code here:
        //Calculated the total fair of all rides
        int column = 9;
        double total=0;
        int rc=jTable1.getRowCount();
        int r=jTable1.getSelectedRow();
        
        for(int i=0;i<rc;i++){
        double fair = (double)jTable1.getModel().getValueAt(i, column);
        
        total=total+fair;
        }
        TotalFairBox.setText(Double.toString(total)+"  taka");
    }//GEN-LAST:event_TotalFairActionPerformed

    private void DriverManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverManagementActionPerformed
        // TODO add your handling code here:
        //Swtiches to Driver management panel
        Driverinformation d=new Driverinformation();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DriverManagementActionPerformed

    private void CustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerManagementActionPerformed
        // TODO add your handling code here:
        //Swtiches to Customer management panel
        Customerinformation c=new Customerinformation();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CustomerManagementActionPerformed
    static Connection connectdb() {
        //Function to establish connection to database and load client driver
        Connection conn = null;
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Uber", "uber", "384142");

            return conn;

        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerManagement;
    private javax.swing.JButton DriverManagement;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton TotalFair;
    private javax.swing.JTextField TotalFairBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
