/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uber;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xenos
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    private boolean check=true,check2=true;
    private int customerid = 0;
    private String name = "", password = "", contact = "";
    Connection conn = null;
    Statement s=null;
    public Customer() {
        
        initComponents();
        
    }

    public Customer(int customerid, String name, String password, String contact) {
        //This construtor overrides the default one so that customer parameters can be taken through login and form switching
        this.contact = contact;
        this.customerid = customerid;
        this.name = name;
        this.password = password;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DriverListButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Refresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AreaComboBox = new javax.swing.JComboBox<>();
        CancelRequest = new javax.swing.JButton();
        RequestService = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DriverListButton.setBackground(new java.awt.Color(204, 0, 0));
        DriverListButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DriverListButton.setText("Get Driver list for selected area");
        DriverListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverListButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DriverListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 260, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver ID", "Driver Name", "Driver Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 490, 100));

        Refresh.setBackground(new java.awt.Color(204, 0, 0));
        Refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thanks for using UBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 250, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("Customer name : "+name);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 340, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("Customer id : "+customerid);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 340, 30));

        AreaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AreaComboBox.setForeground(new java.awt.Color(204, 0, 0));
        AreaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mirpur", "Mohammadpur", "Dhanmondi", "Motijheel", "Tejgaon", "Mohakhali", "Khilgaon", "Gulshan" }));
        jPanel1.add(AreaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 140, 20));

        CancelRequest.setBackground(new java.awt.Color(204, 0, 0));
        CancelRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CancelRequest.setText("Cancel request");
        CancelRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRequestActionPerformed(evt);
            }
        });
        jPanel1.add(CancelRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 130, 30));

        RequestService.setBackground(new java.awt.Color(204, 0, 0));
        RequestService.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RequestService.setText("Request service");
        RequestService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestServiceActionPerformed(evt);
            }
        });
        jPanel1.add(RequestService, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Select a region");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 90, 20));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 380, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Request status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uber/red-gradient-minimalistic-waves-black-abstract-wallpaper-desktop-wallpapers-images-minimalist.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRequestActionPerformed
        // TODO add your handling code here:
        //This code deletes the existing not accepted requests from the request database table based on the current customer id
        check=true;
        check2=true;
        Connection conn = null;
        Statement s = null;
        try {
            
            conn = connectdb();
            String query = "delete from request where id="+""+customerid+"";
            
            s = conn.createStatement();
            s.executeUpdate(query);
            
            conn.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_CancelRequestActionPerformed

    private void RequestServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestServiceActionPerformed
        // TODO add your handling code here:
        //This code adds a request with specified area and customer data to request database table.Check and check2 is used to prevent sending multiple requests by same user and requesting again without submitting current fair.
        if(check&&check2){
        Connection conn = null;
        Statement s = null;
        try {
            String temp = AreaComboBox.getSelectedItem().toString();
            conn = connectdb();
            String query = "insert into request (CUSTOMERNAME, CUSTOMERCONTACT, AREA, ID, AREAID) values('"+name+"','"+contact+"','"+AreaComboBox.getSelectedItem().toString()+"',"+customerid+","+AreaComboBox.getSelectedIndex()+")";
            
            s = conn.createStatement();
            s.executeUpdate(query);
            
            conn.close();

        } catch (Exception e) {
        }
        check=false;
        }
    }//GEN-LAST:event_RequestServiceActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        //This button checks current status of customer request and shows it to request status panel.If any driver accepts the request the panel will display his information.
        Connection conn = null;
        
        Statement s = null;
        try {
            
            conn = connectdb();
            String query = "select * from customers where customerid="+""+customerid+"";
            
            s = conn.createStatement();
            
            ResultSet r=s.executeQuery(query);
            while(r.next()){
            int status=r.getInt(5);
       
            if(status==-1){
                jTextArea1.setText("Sorry no driver has accepted your request yet");
                check2=true;
            }
            else{
                check2=false;
        Statement s2 = null;
            String query2 = "select * from drivers where driverid="+""+status+"";
            s2 = conn.createStatement();
            ResultSet r2=s2.executeQuery(query2);
            while(r2.next()){
            int tdriverid=r2.getInt(1);
            String tdrivename=r2.getString(2);
            String tdrivercontact=r2.getString(4);
                jTextArea1.setText("Driver "+tdrivename+" ,Driver ID : "+tdriverid+" has accepted your request.\nContact him via "+tdrivercontact);
            check=true;
            }
            }
            }
            conn.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void DriverListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverListButtonActionPerformed
        // TODO add your handling code here:
        //This clears the driver list first
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //Then fills with driver data who are operational in the current selected area
        try{
        conn=connectdb();
            s=conn.createStatement();
            ResultSet r=s.executeQuery("select * from drivers where areaid="+""+AreaComboBox.getSelectedIndex()+"");
            while(r.next()){
            int driverid=r.getInt(1);
            String drivername=r.getString(2);
            String drivercontact=r.getString(4);
            model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{driverid,drivername,drivercontact});
            
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_DriverListButtonActionPerformed
    static Connection connectdb() {
        //Function to establish connection to database and load client driver
        Connection conn = null;
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Uber", "uber", "384142");

            return conn;

        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AreaComboBox;
    private javax.swing.JButton CancelRequest;
    private javax.swing.JButton DriverListButton;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton RequestService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
