/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uber;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xenos
 */
public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form Driver
     */
    Connection conn=null;
    Statement s=null;
    private static final DateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
    private boolean check=true;
    private int driverid,areaid,cusid,reqid;
    private String name="",password="",contact="",area="",cusname="",cuscontact="";
    
    public Driver(){
    initComponents();
    }
    public Driver(int driverid,String name,String password,String contact,String area,int areaid) {
        //This construtor overrides the default one so that driver parameters can be taken through login and form switching
        this.contact=contact;
        this.driverid=driverid;
        this.name=name;
        this.password=password;
        this.area=area;
        this.areaid=areaid;
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        AcceptRequest = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FairTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submit.setBackground(new java.awt.Color(204, 0, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, 30));

        Refresh.setBackground(new java.awt.Color(204, 0, 0));
        Refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 150, 30));

        AcceptRequest.setBackground(new java.awt.Color(204, 0, 0));
        AcceptRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AcceptRequest.setText("Accept Request");
        AcceptRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRequestActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Driver area : "+area);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 260, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driver's Panel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request no", "Customer id", "Customer name", "Customer contact no"
            }
        ));
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 520, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Driver name : "+name);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Driver id : "+driverid);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 260, 30));

        FairTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(FairTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 260, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Enter fair amount:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uber/red-gradient-minimalistic-waves-black-abstract-wallpaper-desktop-wallpapers-images-minimalist.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentAdded

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        //Clears the table.
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //The function to refresh requests based on current driver area.
        fetch();
    }//GEN-LAST:event_RefreshActionPerformed

    private void AcceptRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRequestActionPerformed
        // TODO add your handling code here:
        //Accepts the selected request.Works once before submitting the current fair.
        while(check&&(jTable1.getSelectedRow()!=-1)){
        int column = 0;
        int row = jTable1.getSelectedRow();
        String reqid = jTable1.getModel().getValueAt(row, column).toString();
        this.reqid=Integer.parseInt(reqid);
        column=1;
        String customerid = jTable1.getModel().getValueAt(row, column).toString();
        this.cusid=Integer.parseInt(customerid);
        column=2;
        cusname = jTable1.getModel().getValueAt(row, column).toString();
        column=3;
        cuscontact = jTable1.getModel().getValueAt(row, column).toString();
       
        
        Connection conn = null;
        Statement s = null;
        
        Statement s2 = null;
        try {
            
            conn = connectdb();
            String query2 = "update customers set reqstatus="+driverid+" where customerid="+cusid+"";
            s2 = conn.createStatement();
            s2.executeUpdate(query2);
            conn.close();

        } catch (Exception e) {
        }
        check=false;
        }
    }//GEN-LAST:event_AcceptRequestActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        //Submits the fair with driver and customer information and date to ride table,deletes the current request.
        if(FairTextField.getText().isEmpty())
            JOptionPane.showMessageDialog(new JFrame(),"Please enter fair amount!");
        else{
        check=true;
        Connection conn = null;
        Statement s = null;
        try {
            
            conn = connectdb();
            String query = "delete from request where id="+""+cusid+"";
            
            s = conn.createStatement();
            s.executeUpdate(query);
            
            conn.close();

        } catch (Exception e) {
        }
        try {
            Date date = new Date();
         
        String d=sdf.format(date);
        
            conn = connectdb();
            
            String query = "insert into ride (DRIVERID, CUSTOMERID, CUSTOMERNAME, CUSTOMERCONTACT, DRIVERNAME, DRIVERCONTACT, AREA, FAIR, RDATE) values("+driverid+","+cusid+",'"+cusname+"','"+cuscontact+"','"+name+"','"+contact+"','"+area+"',"+Double.parseDouble(FairTextField.getText())+",'"+d+"')";
            
            s = conn.createStatement();
            s.executeUpdate(query);
            
            conn.close();

        } catch (Exception e) {
        }
        Statement s2 = null;
        try {
            
            conn = connectdb();
            String query2 = "update customers set reqstatus="+-1+" where customerid="+cusid+"";
            s2 = conn.createStatement();
            s2.executeUpdate(query2);
            conn.close();

        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_SubmitActionPerformed
    
    static Connection connectdb() {
        //Function to establish connection to database and load client driver
        Connection conn = null;
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Uber", "uber", "384142");

            return conn;

        } catch (Exception e) {
            System.out.println(e);
        }
        return null;
    }
    private void fetch(){
    try {
            
            conn=connectdb();
            s=conn.createStatement();
            ResultSet r=s.executeQuery("select * from request where areaid="+""+areaid+"");
            while(r.next()){
            int reqid1=r.getInt(1);
            String reqid=Integer.toString(reqid1);
            int cusid1=r.getInt(5);
            String cusid=Integer.toString(cusid1);
            String cusname=r.getString(2);
            String cuscontact=r.getString(3);
            String cusarea=r.getString(4);
            
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{reqid,cusid,cusname,cuscontact});
            
            
            }
        } catch (Exception e) {
        }
    
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptRequest;
    private javax.swing.JTextField FairTextField;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
